<?php
 define('DB_HOST', 'localhost');
 define('DB_NAME', 'rr');
 define('DB_USER','root');
 define('DB_PASSWORD','');
 $con=mysql_connect(DB_HOST,DB_USER,DB_PASSWORD) or die("Failed to connect to MySQL: " . mysql_error()); 
 $db=mysql_select_db(DB_NAME,$con) or die("Failed to connect to MySQL: " . mysql_error());

// Check for empty fields
if(empty($_POST['name'])  		||
   empty($_POST['email']) 		||
   empty($_POST['phone']) 		||
   empty($_POST['message']))
   {
	   echo "No arguments Provided!";
	   return false;
	   
   }
   $marketstatus=$_POST['name'];
   $productvalue=$_POST['email'];
   $companycompetitors=$_POST['phone'];
   $existingshare=$_POST['message'];
   $sum=$marketstatus+$productvalue+$companycompetitors+$existingshare;
   $avg=$sum/4;
   $query = mysql_query("INSERT INTO garc_entry VALUES('','$avg',Now())") or die(mysql_error());
   $response_array['status'] = 'success';
   $response_array['average'] ='$avg';
   echo json_encode($response_array);
   //echo "<script language='text/javascript'>function sayHiFromPHP() { alert('Company Market value statically generated by G_ARCH Say's $avg'); }</script>";
   //echo"".$avg;
 ?>  